name: blue_print_pos_new
description: Plugin to connecting bluetooth printer device, support on Android and iOS
version: 0.0.14
homepage: https://github.com/andriyoganp/blue_print_pos

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  # Handler bluetooth for Android
  blue_thermal_printer: any
  # Utilities for generate ByteBuffer
  esc_pos_utils_plus: any
  # Framework
  flutter:
    sdk: flutter
  # Handler bluetooth for iOS
  flutter_blue_plus: any
  # Image utilities
  image: ^3.1.3
  # Generate qr image painter
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ayeee.blue_print_pos
        pluginClass: BluePrintPosPlugin
      ios:
        pluginClass: BluePrintPosPlugin
